name: build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: Validate Code
    runs-on: ubuntu-20.04
    if: github.event_name == 'pull_request' || github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/gradle-build-action@v1
        with:
          arguments: classes ktlintCheck
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    strategy:
      matrix:
        java: [
            17
        ]
        os: [ ubuntu-20.04, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from LTS java on one OS
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
